"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-09 01:59:50.266881
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people')),
    sa.UniqueConstraint('email', name=op.f('uq_people_email'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('seed', 'upload', 'paste', 'form', name='meeting_source', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('processing', 'ready', 'failed', name='meeting_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_meetings_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetings'))
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index('ix_meetings_owner_started', ['owner_id', 'started_at'], unique=False)

    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_chapters_meeting_id_meetings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters'))
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapters_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('meeting_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('speaker_label', sa.String(length=120), nullable=False),
    sa.Column('color_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_participants_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_meeting_participants_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_participants')),
    sa.UniqueConstraint('meeting_id', 'person_id', name=op.f('uq_meeting_participants_meeting_id'))
    )
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_participants_person_id'), ['person_id'], unique=False)

    op.create_table('meeting_tags',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_tags_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_meeting_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', 'tag_id', name=op.f('pk_meeting_tags'))
    )
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.Enum('seed', 'heuristic', 'llm', name='summary_source', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_summaries_meeting_id_meetings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_summaries')),
    sa.UniqueConstraint('meeting_id', name=op.f('uq_summaries_meeting_id'))
    )
    op.create_table('transcript_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_transcript_segments_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['meeting_participants.id'], name=op.f('fk_transcript_segments_participant_id_meeting_participants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript_segments')),
    sa.UniqueConstraint('meeting_id', 'seq', name=op.f('uq_transcript_segments_meeting_id'))
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index('ix_transcript_segments_meeting_start', ['meeting_id', 'start_ms'], unique=False)

    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('assignee_participant_id', sa.Integer(), nullable=True),
    sa.Column('source_segment_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_participant_id'], ['meeting_participants.id'], name=op.f('fk_action_items_assignee_participant_id_meeting_participants'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_action_items_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_segment_id'], ['transcript_segments.id'], name=op.f('fk_action_items_source_segment_id_transcript_segments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_items'))
    )
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_items_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('soundbites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('start_segment_id', sa.Integer(), nullable=False),
    sa.Column('end_segment_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['end_segment_id'], ['transcript_segments.id'], name=op.f('fk_soundbites_end_segment_id_transcript_segments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_soundbites_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['start_segment_id'], ['transcript_segments.id'], name=op.f('fk_soundbites_start_segment_id_transcript_segments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_soundbites'))
    )
    with op.batch_alter_table('soundbites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_soundbites_meeting_id'), ['meeting_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soundbites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soundbites_meeting_id'))

    op.drop_table('soundbites')
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_items_meeting_id'))

    op.drop_table('action_items')
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index('ix_transcript_segments_meeting_start')

    op.drop_table('transcript_segments')
    op.drop_table('summaries')
    op.drop_table('meeting_tags')
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_participants_person_id'))

    op.drop_table('meeting_participants')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_meeting_id'))

    op.drop_table('chapters')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index('ix_meetings_owner_started')

    op.drop_table('meetings')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('people')
    # ### end Alembic commands ###
