"""accounts, per-owner people and tags, uploaded media

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-09 03:23:36.309922
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_status', sa.String(length=200), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_integrations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations'))
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_user_id'), ['user_id'], unique=False)

    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('transport', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_email_log_meeting_id_meetings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_log_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_log'))
    )
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.String(length=100), nullable=True))

    # --- people / tags become private to an account --------------------------------------
    # Existing rows predate accounts, so they all belong to the first (demo) user. Add the column
    # as nullable, backfill, then tighten it.
    for table in ("people", "tags"):
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        op.execute(f"UPDATE {table} SET owner_id = (SELECT id FROM users ORDER BY id LIMIT 1)")
        op.execute(f"DELETE FROM {table} WHERE owner_id IS NULL")  # only possible with no users at all

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('owner_id', existing_type=sa.Integer(), nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_people_email'), type_='unique')
        batch_op.create_index(batch_op.f('ix_people_owner_id'), ['owner_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_people_owner_id'), ['owner_id', 'email'])
        batch_op.create_foreign_key(batch_op.f('fk_people_owner_id_users'), 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('owner_id', existing_type=sa.Integer(), nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_tags_name'), type_='unique')
        batch_op.create_index(batch_op.f('ix_tags_owner_id'), ['owner_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_tags_owner_id'), ['owner_id', 'name'])
        batch_op.create_foreign_key(batch_op.f('fk_tags_owner_id_users'), 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    # --- users: credentials and settings ---------------------------------------------------
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_sub', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('settings', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.create_unique_constraint(batch_op.f('uq_users_google_sub'), ['google_sub'])
    # The pre-accounts seed user is the demo account (it has no password; the demo login handles it)
    op.execute("UPDATE users SET is_demo = 1 WHERE id = (SELECT id FROM users ORDER BY id LIMIT 1)")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_google_sub'), type_='unique')
        batch_op.drop_column('settings')
        batch_op.drop_column('is_demo')
        batch_op.drop_column('google_sub')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tags_owner_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_tags_owner_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_tags_owner_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_tags_name'), ['name'])
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_people_owner_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_people_owner_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_people_owner_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_people_email'), ['email'])
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_path')

    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_log_user_id'))

    op.drop_table('email_log')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_user_id'))

    op.drop_table('integrations')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
